services:
  ganache:
    build: 
      context: ./ganache
      args:
        - "mnemonic=rare shrug lizard style eight pear maple thunder thank explain alert fortune"
    volumes:
      - ./ganache/ganache-db:/db
    ports:
      - 8545:8545
  truffle:
    build: .
    volumes:
      - ./smart-contract:/smart-contract
    depends_on:
      - ganache
    links:
      - ganache
  nextapp:
    restart: always
    build: ./next-app
    ports:
      - 3000:3000
    volumes:
      - ./next-app/pages:/nextapp/pages
      - ./next-app/public:/nextapp/public
      - ./next-app/styles:/nextapp/styles
      - ./next-app/components:/nextapp/components
      #- ./smart-contract:/nextapp/smart-contract
    depends_on:
      - ganache
      - truffle
    links:
      - ganache